services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-review
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrosource_review
    ports:
      - "3305:3306"